

services:
  rstudio:
    image: rocker/verse
    ports:
      - "8787:8787"
    environment:
      PASSWORD: vfci
    command: [ "docker", "run", "--rm", "-ti", "-e","DISABLE_AUTH=true","-p","127.0.0.1:8787:8787"," rocker/verse"]
    volumes:
      - ./.rstudio_config:/home/rstudio/.config/rstudio
      - ~/workspace:/home/rstudio/workspace
      - /workspaces/macro_dynamics:/home/rstudio/macro_dynamics